// This file was generated by counterfeiter
package fakes

import (
	"io"
	"sync"

	. "github.com/concourse/turbine/resource"
)

type FakeTracker struct {
	InitStub        func(typ string, logs io.Writer, abort <-chan struct{}) (Resource, error)
	initMutex       sync.RWMutex
	initArgsForCall []struct {
		arg1 string
		arg2 io.Writer
		arg3 <-chan struct{}
	}
	initReturns struct {
		result1 Resource
		result2 error
	}
	ReleaseStub        func(Resource) error
	releaseMutex       sync.RWMutex
	releaseArgsForCall []struct {
		arg1 Resource
	}
	releaseReturns struct {
		result1 error
	}
}

func (fake *FakeTracker) Init(arg1 string, arg2 io.Writer, arg3 <-chan struct{}) (Resource, error) {
	fake.initMutex.Lock()
	defer fake.initMutex.Unlock()
	fake.initArgsForCall = append(fake.initArgsForCall, struct {
		arg1 string
		arg2 io.Writer
		arg3 <-chan struct{}
	}{arg1, arg2, arg3})
	if fake.InitStub != nil {
		return fake.InitStub(arg1, arg2, arg3)
	} else {
		return fake.initReturns.result1, fake.initReturns.result2
	}
}

func (fake *FakeTracker) InitCallCount() int {
	fake.initMutex.RLock()
	defer fake.initMutex.RUnlock()
	return len(fake.initArgsForCall)
}

func (fake *FakeTracker) InitArgsForCall(i int) (string, io.Writer, <-chan struct{}) {
	fake.initMutex.RLock()
	defer fake.initMutex.RUnlock()
	return fake.initArgsForCall[i].arg1, fake.initArgsForCall[i].arg2, fake.initArgsForCall[i].arg3
}

func (fake *FakeTracker) InitReturns(result1 Resource, result2 error) {
	fake.initReturns = struct {
		result1 Resource
		result2 error
	}{result1, result2}
}

func (fake *FakeTracker) Release(arg1 Resource) error {
	fake.releaseMutex.Lock()
	defer fake.releaseMutex.Unlock()
	fake.releaseArgsForCall = append(fake.releaseArgsForCall, struct {
		arg1 Resource
	}{arg1})
	if fake.ReleaseStub != nil {
		return fake.ReleaseStub(arg1)
	} else {
		return fake.releaseReturns.result1
	}
}

func (fake *FakeTracker) ReleaseCallCount() int {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return len(fake.releaseArgsForCall)
}

func (fake *FakeTracker) ReleaseArgsForCall(i int) Resource {
	fake.releaseMutex.RLock()
	defer fake.releaseMutex.RUnlock()
	return fake.releaseArgsForCall[i].arg1
}

func (fake *FakeTracker) ReleaseReturns(result1 error) {
	fake.releaseReturns = struct {
		result1 error
	}{result1}
}

var _ Tracker = new(FakeTracker)
